# Generated by Django 3.1.7 on 2021-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=30)),
                ('attendance', models.PositiveIntegerField(null=True)),
                ('total_lectures', models.PositiveIntegerField(null=True)),
                ('marks', models.PositiveIntegerField(null=True)),
                ('total_marks', models.PositiveIntegerField(null=True)),
                ('name', models.ManyToManyField(to='accounts.student')),
            ],
        ),
    ]
