# Generated by Django 3.1.7 on 2021-05-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210501_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='email',
        ),
    ]
