# Generated by Django 3.1.7 on 2021-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subject_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='population',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
